add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

# Show directory and language version above the prompt
# format = "[$directory$git_branch$git_status]($style)$character"
format = """
$directory
$git_branch
$git_status
$git_commit
$character
"""

# Only show time on the right, flush with the edge
right_format = """
$time
"""

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = "[→](bold green)"
error_symbol = "[→](bold red)"
vimcmd_symbol = "[→](bold green)"
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "▼"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[sudo]
format = "[$symbol]($style)"
style = "bold italic mauve"
symbol = "⋈┈"
disabled = false

[username]
style_user = "blue bold"
style_root = "red bold"
format = "[$user](blue bold) "
disabled = false
show_always = true

[directory]
home_symbol = "⌂"
truncation_length = 2
truncation_symbol = "□ "
read_only = " ◈"
use_os_path_sep = true
style = "blue"
format = '[$path]($style)[$read_only]($read_only_style)'

[nodejs]
format = " via [ $version](bold green)"
version_format = "${raw}"
symbol = ""
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[python]
format = " via [ $version](bold yellow)"
symbol = ""
version_format = "${raw}"

[rust]
format = " via [ $version](bold peach)"
symbol = ""
version_format = "${raw}"

[lua]
format = " via [ $version](bold blue)"
symbol = ""
version_format = "${raw}"

[deno]
format = " via [🦕 $version](bold cyan)"
version_format = "${raw}"

[package]
format = " [pkg $version](yellow italic bold)"
version_format = "${raw}"
symbol = ""

[cmd_duration]
format = "[◄ $duration ](italic overlay0)"

[jobs]
format = "[$symbol$number]($style) "
style = "text"
symbol = "[▶](blue italic)"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold mauve)"
disabled = false

[time]
disabled = false
format = "[ $time](overlay0)"
time_format = "%R"
utc_time_offset = "local"
style = "overlay0"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "█"
charging_symbol = "[↑](italic bold green)"
discharging_symbol = "↓"
unknown_symbol = "░"
empty_symbol = "▃"

[[battery.display]]
threshold = 20
style = "italic bold red"

[[battery.display]]
threshold = 60
style = "italic mauve"

[[battery.display]]
threshold = 70
style = "italic yellow"

[git_branch]
format = " [$branch(:$remote_branch)]($style)"
symbol = "[△](bold italic blue)"
style = "italic red"
truncation_symbol = "⋯"
truncation_length = 11
# ignore_branches = ["main", "master"]
only_attached = true

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'italic green'
deleted_style = 'italic red'
ignore_submodules = true
disabled = false

[git_status]
style = "bold italic blue"
format = "([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"
conflicted = "[◪◦](italic mauve)"
ahead = "[▴│[${count}](bold text)│](italic green)"
behind = "[▿│[${count}](bold text)│](italic red)"
diverged = "[◇ ▴┤[${ahead_count}](text)│▿┤[${behind_count}](text)│](italic mauve)"
untracked = "[◌◦](italic yellow)"
stashed = "[◃◈](italic text)"
modified = "[●◦](italic peach)"
staged = "[▪┤[$count](bold text)│](italic teal)"
renamed = "[◎◦](italic blue)"
deleted = "[✕](italic red)"


[git_commit]
disabled = false
only_detached = false
format = ' [ $hash](fg:color_pink)'
commit_hash_length = 6
tag_disabled = false
