set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g prefix C-a
set -g renumber-windows on
set -g status-position top
set -g status-justify absolute-centre
set -g base-index 1
setw -g pane-base-index 1
set -g status-left "#S"
set -g status-right ""
set -g status-style "fg=default,bg=default"
set -g window-status-format "#I:#W"
set -g window-status-current-format "#I:#W"
set -g window-status-style "fg=default,bg=default,nobold,noitalics,nounderscore"
set -g window-status-current-style "fg=default,bg=default,nobold,noitalics,nounderscore"
set -g window-status-separator " "
set -g pane-border-style "fg=default,bg=default"
set -g pane-active-border-style "fg=default,bg=default"
set -g message-style "fg=default,bg=default"
set -g mode-style "fg=default,bg=default"

bind r source-file ~/.config/tmux/tmux.conf
bind x kill-window

unbind %
bind [ split-window -h 
unbind '"'
bind ] split-window -v

bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
bind h resize-pane -L 5


set -g mouse on

set -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

setw -g automatic-rename on   # rename window to reflect current program

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'frizadiga/tmux-float-term'


unbind e
set -g @tmux-float-term-bind 'e'                    # Key binding to toggle floating terminal
# set -g @tmux-float-term-maximize-bind 'A'           # Key binding to toggle maximized floating terminal
set -g @tmux-float-term-width '60%'                 # Width of regular floating terminal
set -g @tmux-float-term-height '60%'                # Height of regular floating terminal
set -g @tmux-float-term-max-width '90%'             # Width of maximized floating terminal
set -g @tmux-float-term-max-height '90%'            # Height of maximized floating terminal
set -g @tmux-float-term-text-color 'white'          # Text color
set -g @tmux-float-term-border-color 'grey'         # Border color
set -g @tmux-float-term-title ''                    # Custom title for the floating terminal
set -g @tmux-float-term-change-path 'true'          # Change to current pane's path
set -g @tmux-float-term-session-name 'float-term'  # Name of the floating session

set -g @vim_navigator_mapping_left "C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

run '~/dotfiles/tmux/plugins/tpm/tpm'
