set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g prefix C-a
set -g renumber-windows on
set -g status-position top
set -g status-justify absolute-centre
set -g base-index 1
setw -g pane-base-index 1
set -g status-left "#S"
set -g status-right ""
set -g status-style "fg=default,bg=default"
set -g window-status-format "#I:#W"
set -g window-status-current-format "#I:#W"
set -g window-status-style "fg=default,bg=default,nobold,noitalics,nounderscore"
set -g window-status-current-style "fg=default,bg=default,nobold,noitalics,nounderscore"
set -g window-status-separator " "
set -g pane-border-style "fg=default,bg=default"
set -g pane-active-border-style "fg=default,bg=default"
set -g message-style "fg=default,bg=default"
set -g mode-style "fg=default,bg=default"

unbind-key C-b

# Set the new prefix to Ctrl-a
set-option -g prefix C-a

bind r source-file ~/dotfiles/nix/config/tmux/tmux.conf
bind x kill-window

unbind %
bind ] split-window -h 
unbind '"'
bind [ split-window -v

bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
bind h resize-pane -L 5


set -g mouse on

set -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

setw -g automatic-rename on   # rename window to reflect current program

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind C-l send-keys 'C-l'
bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l


set -g @plugin 'frizadiga/tmux-float-term'
unbind e
set -g @tmux-float-term-bind 'e'                    # Key binding to toggle floating terminal
set -g @tmux-float-term-maximize-bind 'A'           # Key binding to toggle maximized floating terminal
set -g @tmux-float-term-width '60%'                 # Width of regular floating terminal
set -g @tmux-float-term-height '60%'                # Height of regular floating terminal
set -g @tmux-float-term-max-width '90%'             # Width of maximized floating terminal
set -g @tmux-float-term-max-height '90%'            # Height of maximized floating terminal
set -g @tmux-float-term-text-color 'white'          # Text color
set -g @tmux-float-term-border-color 'grey'         # Border color
set -g @tmux-float-term-title ''                    # Custom title for the floating terminal
set -g @tmux-float-term-change-path 'true'          # Change to current pane's path
set -g @tmux-float-term-session-name 'float-term'  # Name of the floating session

set -g @vim_navigator_mapping_left "C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

run '~/dotfiles/tmux/plugins/tpm/tpm'
